/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using AsanaNet.Client;
using AsanaNet.Api;
// uncomment below to import models
//using AsanaNet.Model;

namespace AsanaNet.Test.Api
{
    /// <summary>
    ///  Class for testing ProjectBriefsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProjectBriefsApiTests : IDisposable
    {
        private ProjectBriefsApi instance;

        public ProjectBriefsApiTests()
        {
            instance = new ProjectBriefsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProjectBriefsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ProjectBriefsApi
            //Assert.IsType<ProjectBriefsApi>(instance);
        }

        /// <summary>
        /// Test CreateProjectBrief
        /// </summary>
        [Fact]
        public void CreateProjectBriefTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectGid = null;
            //UpdateProjectBriefRequest updateProjectBriefRequest = null;
            //bool? optPretty = null;
            //List<string>? optFields = null;
            //var response = instance.CreateProjectBrief(projectGid, updateProjectBriefRequest, optPretty, optFields);
            //Assert.IsType<GetProjectBrief200Response>(response);
        }

        /// <summary>
        /// Test DeleteProjectBrief
        /// </summary>
        [Fact]
        public void DeleteProjectBriefTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectBriefGid = null;
            //bool? optPretty = null;
            //var response = instance.DeleteProjectBrief(projectBriefGid, optPretty);
            //Assert.IsType<DeleteAttachment200Response>(response);
        }

        /// <summary>
        /// Test GetProjectBrief
        /// </summary>
        [Fact]
        public void GetProjectBriefTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectBriefGid = null;
            //bool? optPretty = null;
            //List<string>? optFields = null;
            //var response = instance.GetProjectBrief(projectBriefGid, optPretty, optFields);
            //Assert.IsType<GetProjectBrief200Response>(response);
        }

        /// <summary>
        /// Test UpdateProjectBrief
        /// </summary>
        [Fact]
        public void UpdateProjectBriefTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectBriefGid = null;
            //UpdateProjectBriefRequest updateProjectBriefRequest = null;
            //bool? optPretty = null;
            //List<string>? optFields = null;
            //var response = instance.UpdateProjectBrief(projectBriefGid, updateProjectBriefRequest, optPretty, optFields);
            //Assert.IsType<GetProjectBrief200Response>(response);
        }
    }
}
