/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using AsanaNet.Client;
using AsanaNet.Api;
// uncomment below to import models
//using AsanaNet.Model;

namespace AsanaNet.Test.Api
{
    /// <summary>
    ///  Class for testing TeamMembershipsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TeamMembershipsApiTests : IDisposable
    {
        private TeamMembershipsApi instance;

        public TeamMembershipsApiTests()
        {
            instance = new TeamMembershipsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TeamMembershipsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TeamMembershipsApi
            //Assert.IsType<TeamMembershipsApi>(instance);
        }

        /// <summary>
        /// Test GetTeamMembership
        /// </summary>
        [Fact]
        public void GetTeamMembershipTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string teamMembershipGid = null;
            //bool? optPretty = null;
            //List<string>? optFields = null;
            //var response = instance.GetTeamMembership(teamMembershipGid, optPretty, optFields);
            //Assert.IsType<GetTeamMembership200Response>(response);
        }

        /// <summary>
        /// Test GetTeamMemberships
        /// </summary>
        [Fact]
        public void GetTeamMembershipsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? optPretty = null;
            //int? limit = null;
            //string? offset = null;
            //string? team = null;
            //string? user = null;
            //string? workspace = null;
            //List<string>? optFields = null;
            //var response = instance.GetTeamMemberships(optPretty, limit, offset, team, user, workspace, optFields);
            //Assert.IsType<GetTeamMemberships200Response>(response);
        }

        /// <summary>
        /// Test GetTeamMembershipsForTeam
        /// </summary>
        [Fact]
        public void GetTeamMembershipsForTeamTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string teamGid = null;
            //bool? optPretty = null;
            //int? limit = null;
            //string? offset = null;
            //List<string>? optFields = null;
            //var response = instance.GetTeamMembershipsForTeam(teamGid, optPretty, limit, offset, optFields);
            //Assert.IsType<GetTeamMemberships200Response>(response);
        }

        /// <summary>
        /// Test GetTeamMembershipsForUser
        /// </summary>
        [Fact]
        public void GetTeamMembershipsForUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userGid = null;
            //string workspace = null;
            //bool? optPretty = null;
            //int? limit = null;
            //string? offset = null;
            //List<string>? optFields = null;
            //var response = instance.GetTeamMembershipsForUser(userGid, workspace, optPretty, limit, offset, optFields);
            //Assert.IsType<GetTeamMemberships200Response>(response);
        }
    }
}
