/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AsanaNet.Client.OpenAPIDateConverter;

namespace AsanaNet.Model
{
    /// <summary>
    /// AddMembersRequest
    /// </summary>
    [DataContract(Name = "AddMembersRequest")]
    public partial class AddMembersRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddMembersRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddMembersRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddMembersRequest" /> class.
        /// </summary>
        /// <param name="members">An array of strings identifying users. These can either be the string \&quot;me\&quot;, an email, or the gid of a user. (required).</param>
        public AddMembersRequest(string members = default(string))
        {
            // to ensure "members" is required (not null)
            if (members == null)
            {
                throw new ArgumentNullException("members is a required property for AddMembersRequest and cannot be null");
            }
            this.Members = members;
        }

        /// <summary>
        /// An array of strings identifying users. These can either be the string \&quot;me\&quot;, an email, or the gid of a user.
        /// </summary>
        /// <value>An array of strings identifying users. These can either be the string \&quot;me\&quot;, an email, or the gid of a user.</value>
        /// <example>521621,621373</example>
        [DataMember(Name = "members", IsRequired = true, EmitDefaultValue = true)]
        public string Members { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddMembersRequest {\n");
            sb.Append("  Members: ").Append(Members).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
