/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AsanaNet.Client.OpenAPIDateConverter;

namespace AsanaNet.Model
{
    /// <summary>
    /// DateVariableRequest
    /// </summary>
    [DataContract(Name = "DateVariableRequest")]
    public partial class DateVariableRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DateVariableRequest" /> class.
        /// </summary>
        /// <param name="gid">Globally unique identifier of the date field in the project template. A value of &#x60;1&#x60; refers to the project start date, while &#x60;2&#x60; refers to the project due date..</param>
        /// <param name="value">The date with which the date variable should be replaced when instantiating a project. This takes a date with &#x60;YYYY-MM-DD&#x60; format..</param>
        public DateVariableRequest(string gid = default(string), DateTime? value = default(DateTime?))
        {
            this.Gid = gid;
            this.Value = value;
        }

        /// <summary>
        /// Globally unique identifier of the date field in the project template. A value of &#x60;1&#x60; refers to the project start date, while &#x60;2&#x60; refers to the project due date.
        /// </summary>
        /// <value>Globally unique identifier of the date field in the project template. A value of &#x60;1&#x60; refers to the project start date, while &#x60;2&#x60; refers to the project due date.</value>
        /// <example>1</example>
        [DataMember(Name = "gid", EmitDefaultValue = false)]
        public string Gid { get; set; }

        /// <summary>
        /// The date with which the date variable should be replaced when instantiating a project. This takes a date with &#x60;YYYY-MM-DD&#x60; format.
        /// </summary>
        /// <value>The date with which the date variable should be replaced when instantiating a project. This takes a date with &#x60;YYYY-MM-DD&#x60; format.</value>
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public DateTime? Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DateVariableRequest {\n");
            sb.Append("  Gid: ").Append(Gid).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
