/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AsanaNet.Client.OpenAPIDateConverter;

namespace AsanaNet.Model
{
    /// <summary>
    /// GoalRemoveSupportingRelationshipRequest
    /// </summary>
    [DataContract(Name = "GoalRemoveSupportingRelationshipRequest")]
    public partial class GoalRemoveSupportingRelationshipRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GoalRemoveSupportingRelationshipRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GoalRemoveSupportingRelationshipRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GoalRemoveSupportingRelationshipRequest" /> class.
        /// </summary>
        /// <param name="supportingResource">The gid of the supporting resource to remove from the parent goal. Must be the gid of a goal, project, task, or portfolio. (required).</param>
        public GoalRemoveSupportingRelationshipRequest(string supportingResource = default(string))
        {
            // to ensure "supportingResource" is required (not null)
            if (supportingResource == null)
            {
                throw new ArgumentNullException("supportingResource is a required property for GoalRemoveSupportingRelationshipRequest and cannot be null");
            }
            this.SupportingResource = supportingResource;
        }

        /// <summary>
        /// The gid of the supporting resource to remove from the parent goal. Must be the gid of a goal, project, task, or portfolio.
        /// </summary>
        /// <value>The gid of the supporting resource to remove from the parent goal. Must be the gid of a goal, project, task, or portfolio.</value>
        /// <example>12345</example>
        [DataMember(Name = "supporting_resource", IsRequired = true, EmitDefaultValue = true)]
        public string SupportingResource { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GoalRemoveSupportingRelationshipRequest {\n");
            sb.Append("  SupportingResource: ").Append(SupportingResource).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
