/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AsanaNet.Client.OpenAPIDateConverter;

namespace AsanaNet.Model
{
    /// <summary>
    /// RemoveCustomFieldSettingRequest
    /// </summary>
    [DataContract(Name = "RemoveCustomFieldSettingRequest")]
    public partial class RemoveCustomFieldSettingRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemoveCustomFieldSettingRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RemoveCustomFieldSettingRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RemoveCustomFieldSettingRequest" /> class.
        /// </summary>
        /// <param name="customField">The custom field to remove from this portfolio. (required).</param>
        public RemoveCustomFieldSettingRequest(string customField = default(string))
        {
            // to ensure "customField" is required (not null)
            if (customField == null)
            {
                throw new ArgumentNullException("customField is a required property for RemoveCustomFieldSettingRequest and cannot be null");
            }
            this.CustomField = customField;
        }

        /// <summary>
        /// The custom field to remove from this portfolio.
        /// </summary>
        /// <value>The custom field to remove from this portfolio.</value>
        /// <example>14916</example>
        [DataMember(Name = "custom_field", IsRequired = true, EmitDefaultValue = true)]
        public string CustomField { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RemoveCustomFieldSettingRequest {\n");
            sb.Append("  CustomField: ").Append(CustomField).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
