/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AsanaNet.Client.OpenAPIDateConverter;

namespace AsanaNet.Model
{
    /// <summary>
    /// RequestedRoleRequest
    /// </summary>
    [DataContract(Name = "RequestedRoleRequest")]
    public partial class RequestedRoleRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestedRoleRequest" /> class.
        /// </summary>
        /// <param name="gid">Globally unique identifier of the template role in the project template..</param>
        /// <param name="value">The user id that should be assigned to the template role..</param>
        public RequestedRoleRequest(string gid = default(string), string value = default(string))
        {
            this.Gid = gid;
            this.Value = value;
        }

        /// <summary>
        /// Globally unique identifier of the template role in the project template.
        /// </summary>
        /// <value>Globally unique identifier of the template role in the project template.</value>
        /// <example>1</example>
        [DataMember(Name = "gid", EmitDefaultValue = false)]
        public string Gid { get; set; }

        /// <summary>
        /// The user id that should be assigned to the template role.
        /// </summary>
        /// <value>The user id that should be assigned to the template role.</value>
        /// <example>123</example>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RequestedRoleRequest {\n");
            sb.Append("  Gid: ").Append(Gid).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
