/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AsanaNet.Model;
using AsanaNet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AsanaNet.Test.Model
{
    /// <summary>
    ///  Class for testing CustomFieldCompactAllOfDateValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomFieldCompactAllOfDateValueTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomFieldCompactAllOfDateValue
        //private CustomFieldCompactAllOfDateValue instance;

        public CustomFieldCompactAllOfDateValueTests()
        {
            // TODO uncomment below to create an instance of CustomFieldCompactAllOfDateValue
            //instance = new CustomFieldCompactAllOfDateValue();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomFieldCompactAllOfDateValue
        /// </summary>
        [Fact]
        public void CustomFieldCompactAllOfDateValueInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomFieldCompactAllOfDateValue
            //Assert.IsType<CustomFieldCompactAllOfDateValue>(instance);
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

        /// <summary>
        /// Test the property 'DateTime'
        /// </summary>
        [Fact]
        public void DateTimeTest()
        {
            // TODO unit test for the property 'DateTime'
        }
    }
}
