/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AsanaNet.Model;
using AsanaNet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AsanaNet.Test.Model
{
    /// <summary>
    ///  Class for testing GoalCompactAllOfOwner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GoalCompactAllOfOwnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GoalCompactAllOfOwner
        //private GoalCompactAllOfOwner instance;

        public GoalCompactAllOfOwnerTests()
        {
            // TODO uncomment below to create an instance of GoalCompactAllOfOwner
            //instance = new GoalCompactAllOfOwner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GoalCompactAllOfOwner
        /// </summary>
        [Fact]
        public void GoalCompactAllOfOwnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GoalCompactAllOfOwner
            //Assert.IsType<GoalCompactAllOfOwner>(instance);
        }

        /// <summary>
        /// Test the property 'Gid'
        /// </summary>
        [Fact]
        public void GidTest()
        {
            // TODO unit test for the property 'Gid'
        }

        /// <summary>
        /// Test the property 'ResourceType'
        /// </summary>
        [Fact]
        public void ResourceTypeTest()
        {
            // TODO unit test for the property 'ResourceType'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
