/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AsanaNet.Model;
using AsanaNet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AsanaNet.Test.Model
{
    /// <summary>
    ///  Class for testing GoalResponseAllOfCurrentStatusUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GoalResponseAllOfCurrentStatusUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GoalResponseAllOfCurrentStatusUpdate
        //private GoalResponseAllOfCurrentStatusUpdate instance;

        public GoalResponseAllOfCurrentStatusUpdateTests()
        {
            // TODO uncomment below to create an instance of GoalResponseAllOfCurrentStatusUpdate
            //instance = new GoalResponseAllOfCurrentStatusUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GoalResponseAllOfCurrentStatusUpdate
        /// </summary>
        [Fact]
        public void GoalResponseAllOfCurrentStatusUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" GoalResponseAllOfCurrentStatusUpdate
            //Assert.IsType<GoalResponseAllOfCurrentStatusUpdate>(instance);
        }

        /// <summary>
        /// Test the property 'Gid'
        /// </summary>
        [Fact]
        public void GidTest()
        {
            // TODO unit test for the property 'Gid'
        }

        /// <summary>
        /// Test the property 'ResourceType'
        /// </summary>
        [Fact]
        public void ResourceTypeTest()
        {
            // TODO unit test for the property 'ResourceType'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'ResourceSubtype'
        /// </summary>
        [Fact]
        public void ResourceSubtypeTest()
        {
            // TODO unit test for the property 'ResourceSubtype'
        }
    }
}
